### ISSUE TITLE
B占无法推送

### ISSUE THREAD

**Issue by onlyzqy** [snowtafir/xianxin-plugin#2]
[TRSSYz][22:08:20.041][ERRO] 定时任务报错：xianxin插件---B站推送定时任务
[TRSSYz][22:08:20.041][ERRO] TypeError: Cannot read properties of null (reading 'code')
    at Bilibili.getBilibiliDynamicInfo (file:///mnt/Disk1/Yunzai/plugins/trss-xianxin-plugin/model/bilibili.js:154:33)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at process.processTimers (node:internal/timers:504:9)
    at async Bilibili.upTask (file:///mnt/Disk1/Yunzai/plugins/trss-xianxin-plugin/model/bilibili.js:236:26)
    at async bilibili.newPushTask (file:///mnt/Disk1/Yunzai/plugins/trss-xianxin-plugin/apps/bilibili.js:115:5)
    at async Job.job (file:///mnt/Disk1/Yunzai/lib/plugins/loader.js:616:48)

**Comment by snowtafir** [comment]
> [TRSSYz][22:08:20.041][ERRO] 定时任务报错：xianxin插件---B站推送定时任务 [TRSSYz][22:08:20.041][ERRO] TypeError: Cannot read properties of null (reading 'code') at Bilibili.getBilibiliDynamicInfo (file:///mnt/Disk1/Yunzai/plugins/trss-xianxin-plugin/model/bilibili.js:154:33) at processTicksAndRejections (node:internal/process/task_queues:95:5) at runNextTicks (node:internal/process/task_queues:64:3) at process.processTimers (node:internal/timers:504:9) at async Bilibili.upTask (file:///mnt/Disk1/Yunzai/plugins/trss-xianxin-plugin/model/bilibili.js:236:26) at async bilibili.newPushTask (file:///mnt/Disk1/Yunzai/plugins/trss-xianxin-plugin/apps/bilibili.js:115:5) at async Job.job (file:///mnt/Disk1/Yunzai/lib/plugins/loader.js:616:48)

更新，发送命令 `#刷新b站临时ck`， 每2天执行一次
